[project]
name = "chatbot-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "numpy>=2.5.3",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "requests>=2.32.0",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.36.0",
]
